spring:
  kafka:
    bootstrap-servers: localhost:9092
    numPartitions: 1
    replicationFactor: 1
    topics:
      simple-message:
        name: simple_message

schema-registry:
  host: http://localhost:9090
  uri: /apis/registry/v2